swagger: '2.0'
info:
  title: FunctionAppB
  version: v1
host: endjinfunctionappb.azurewebsites.net
schemes:
  - https
paths:
  /api/operation/b:
    post:
      tags:
        - Operation
      summary: Operation - B
      operationId: Operation_B
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: request
          in: body
          description: >-
            Performs Operation B
          required: true
          schema:
            $ref: '#/definitions/FunctionBRequest'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/FunctionBResponse'
definitions:
  FunctionBRequest:
    type: object
    properties:
      Id:
        type: string
      Content:
        type: string
    example:
      id: 456
      content: goodbye
  FunctionBResponse:
    type: object
    properties:
      Result:
        type: string
    example:
      result: 456 goodbye