swagger: '2.0'
info:
  title: FunctionAppA
  version: v1
host: endjinfunctionappa.azurewebsites.net
schemes:
  - https
paths:
  /api/operation/a:
    post:
      tags:
        - Operation
      summary: Operation - A
      operationId: Operation_A
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: request
          in: body
          description: >-
            Performs Operation A
          required: true
          schema:
            $ref: '#/definitions/FunctionARequest'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/FunctionAResponse'
definitions:
  FunctionARequest:
    type: object
    properties:
      Id:
        type: string
      Content:
        type: string
    example:
      id: 123
      content: hello
  FunctionAResponse:
    type: object
    properties:
      Result:
        type: string
    example:
      result: 123 hello